include_guard(GLOBAL)

set(MYPROJECT_BUILD_IS_DEBUG FALSE)
set(MYPROJECT_BUILD_IS_RELEASE FALSE)
set(MYPROJECT_BUILD_IS_RELWITHDEBINFO FALSE)

if(CMAKE_BUILD_TYPE STREQUAL "Debug")
  set(MYPROJECT_BUILD_IS_DEBUG TRUE)
elseif(CMAKE_BUILD_TYPE STREQUAL "Release")
  set(MYPROJECT_BUILD_IS_RELEASE TRUE)
elseif(CMAKE_BUILD_TYPE STREQUAL "RelWithDebInfo")
  set(MYPROJECT_BUILD_IS_RELWITHDEBINFO TRUE)
endif()
