include(${CMAKE_SOURCE_DIR}/cmake/CompilerDetection.cmake)

function(myproject_configure_target_exceptions target)
  if(myproject_DISABLE_EXCEPTIONS)
    if(NOT (DEFINED RUST_FEATURES AND RUST_FEATURES))
      myproject_is_msvc_compiler(IS_MSVC)
      myproject_is_clang_cl(IS_CLANG_CL)
      myproject_is_unix_like_compiler(IS_UNIX_LIKE)

      if(IS_MSVC)
        target_compile_options(${target} PUBLIC /EHs-)
      elseif(IS_CLANG_CL)
        target_compile_options(${target} PUBLIC /EHs-)
      elseif(IS_UNIX_LIKE)
        target_compile_options(${target} PUBLIC -fno-exceptions)
      endif()
    endif()
  else()
    myproject_is_msvc_compiler(IS_MSVC)
    myproject_is_clang_cl(IS_CLANG_CL)
    myproject_is_unix_like_compiler(IS_UNIX_LIKE)

    if(IS_MSVC)
      target_compile_options(${target} PUBLIC /EHsc)
    elseif(IS_CLANG_CL)
      target_compile_options(${target} PUBLIC /EHsc)
    elseif(IS_UNIX_LIKE)
      target_compile_options(${target} PUBLIC -fexceptions)
    endif()
  endif()
endfunction()
