name: Main CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build-gcc-x64:
    uses: ./.github/workflows/linux_run.yml
    with:
      compiler: gcc
      runner: ubuntu-24.04-arm

  build-clang-arm:
    uses: ./.github/workflows/linux_run.yml
    with:
      compiler: clang
      runner: ubuntu-24.04-arm
